### PR TITLE
List of dependencies for audit

### PR DESCRIPTION
**Pull request by mpguerra**
Starting a list here as an example. If we don't think we want to put it in the same sort of place as Zebra, let's move it elsewhere

### CODE REVIEW

**Comment by conradoplg** [comment]
I think that's pretty much it :+1: 

One thing I'm wondering about are the underlying crates with the elliptic curve implementations. In particular `ed448-goldilocks`  which is not as mature as the other ones. Is this something that we're willing to include in the audit?

**Comment by mpguerra** [comment]
> One thing I'm wondering about are the underlying crates with the elliptic curve implementations. In particular `ed448-goldilocks` which is not as mature as the other ones. Is this something that we're willing to include in the audit?

Maybe we can do a partial audit of the code that is used by FROST

**Comment by mpguerra** [comment]
Actually, let's just leave it out altogether

**Comment by mpguerra** [comment]
> One thing I'm wondering about are the underlying crates with the elliptic curve implementations. In particular `ed448-goldilocks` which is not as mature as the other ones. Is this something that we're willing to include in the audit?

@chelseakomlo do you have any thoughts on this? I'd vote to leave them all out unless there's any you'd be particularly interested in getting partially audited, e.g the parts that are used by FROST code. 

Otherwise let's just close this list, merge the PR and move things forward.

**Review by dconnolly — APPROVED** [review]

**Comment by dconnolly** [comment]
> > One thing I'm wondering about are the underlying crates with the elliptic curve implementations. In particular `ed448-goldilocks` which is not as mature as the other ones. Is this something that we're willing to include in the audit?
> 
> @chelseakomlo do you have any thoughts on this? I'd vote to leave them all out unless there's any you'd be particularly interested in getting partially audited, e.g the parts that are used by FROST code.
> 
> Otherwise let's just close this list, merge the PR and move things forward.

I think auditing each of these curve libs is a big scope increase; when we had redjubjub FROST audited they looked at the top-level library and not the `jubjub` dependency

**Pull request merged**
