### PR TITLE
CI: Clippy, linting, check rustdoc, etc

### PR DESCRIPTION
**Pull request by dconnolly**

### CODE REVIEW

**Comment by dconnolly** [comment]
@conradoplg I am ignoring `frost-redjubjub` in the Cargo workspace for now, we should un-ignore it when your re-randomization stuff gets merged (or whatever is most appropriate)

**Comment by conradoplg** [comment]
Cool! 

I fixed some lints [here](https://github.com/ZcashFoundation/frost/pull/88) so you might want to merge that first.

**Comment by dconnolly** [comment]
@mergify

**Comment by dconnolly** [comment]
@Mergifyio rebase

**Comment by dconnolly** [comment]
@mergify rebase

**Pull request merged**
